# Generated by Django 6.0.4 on 2026-10-01 23:23

import accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use international format,eg +23480123456789')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('trade', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=200)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('pin_lockdown', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('hard_capacity', models.PositiveIntegerField(help_text='Maximum people allowed on site at once (from the fire safety plan).', validators=[django.core.validators.MinValueValidator(1)])),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=64, validators=[accounts.models.validate_timzone])),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='accounts.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('tokens_exp', models.DateTimeField(default=accounts.models.token_expires)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{7,14}$', 'Use international format,eg +23480123456789')])),
                ('role', models.CharField(choices=[('PLATFORMADMIN', 'Platform Admin'), ('SITEADMIN', 'Site Admin'), ('SUPERVISORS', 'Supervisors'), ('WORKER', 'Worker')], max_length=200)),
                ('trade', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Invite'), ('ACCEPTED', 'Accepted Invite'), ('REJECTED', 'Rejected Invite'), ('REVOKED', 'Revoked Invite')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invited_by_user', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invited_to_organisation', to='accounts.organisation')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invited_to_site', to='accounts.site')),
            ],
        ),
        migrations.CreateModel(
            name='SiteLinks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.CharField(choices=[('PLATFORMADMIN', 'Platform Admin'), ('SITEADMIN', 'Site Admin'), ('SUPERVISORS', 'Supervisors'), ('WORKER', 'Worker')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_sites', to='accounts.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('organisation', 'employee_id'), name='unique_employee_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_site_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('organisation', 'phone'), name='one_pending_invite_per_phone_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'PLATFORMADMIN'), ('sites__isnull', True)), models.Q(models.Q(('role', 'PLATFORMADMIN'), _negated=True), ('sites__isnull', False)), _connector='OR'), name='invite_site_matches_role'),
        ),
        migrations.AddConstraint(
            model_name='sitelinks',
            constraint=models.UniqueConstraint(fields=('user', 'site', 'roles'), name='unique_role_per_user_per_site'),
        ),
    ]
