# Generated by Django 6.0.4 on 2026-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('PLATFORMADMIN', 'Platform Admin'), ('SITEADMIN', 'Site Admin'), ('SUPERVISORS', 'Supervisors'), ('WORKER', 'Worker')], max_length=100, null=True),
        ),
    ]
